### ISSUE TITLE
bidirectional edges

### ISSUE THREAD

**Issue by andrewsu** [stuppie/WikiDataScape#5]
when two nodes have reciprocal property relationships, add a bidirectional edge or two unidirectional edges

**Comment by stuppie** [comment]
![image](https://cloud.githubusercontent.com/assets/5470131/17531482/dd3f9892-5e30-11e6-8350-7889805bd74b.png)
Can even have multiple directional edges if two nodes are linked by >1 property!

**Comment by stuppie** [comment]
https://github.com/stuppie/WikiDataScape/commit/9384dfd106923b1425641394a7e996d439dafe90#diff-b21a49ecdcfbc2d01692a58f3a6949eaR115
