### ISSUE TITLE
dynamically color nodes based on subclass or instance properties

### ISSUE THREAD

**Issue by andrewsu** [stuppie/WikiDataScape#7]

**Comment by stuppie** [comment]
Can't get this to work. No documentation...
https://github.com/stuppie/WikiDataScape/blob/master/src/main/java/org/cytoscape/WikiDataScape/internal/tasks/SetVisualStyleTask.java

**Comment by stuppie** [comment]
https://github.com/stuppie/WikiDataScape/commit/74f68fb832129e525cfd46b70a5171735d71a9f4
